# CONFIG
[theme]
primaryColor = "#2e7d32"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[server]
maxUploadSize = 20
enableXsrfProtection = true
headless = false

[logger]
level = "info"

[browser]
gatherUsageStats = false
